### ISSUE TITLE
Composer support

### ISSUE THREAD

**Issue by dmyers** [iamcal/php-emoji#11]
Can you add a composer.json and add to [Packagist](http://packagist.org)?

**Comment by budhead** [comment]
+1

**Comment by marktopper** [comment]
:+1:

**Comment by marktopper** [comment]
While it is not added to composer you can however use this in you composer.json file to require it anyways.

```
{
    // ...
    "repositories": {
        "php-emoji": {
            "type": "package",
            "package": {
                "name": "iamcal/php-emoji",
                "version": "1.0.0",
                "source": {
                    "url": "https://github.com/iamcal/php-emoji",
                    "type": "git",
                    "reference": "dev-master"
                }
            }
        }
    },
    // ...
    "require": {
        // ...
        "iamcal/php-emoji": "1.0.0"
        // ...
    },
    // ...
}
```

Enjoy.

**Comment by KristobalJunta** [comment]
+1 for this

**Comment by iamcal** [comment]
If somebody wants to PR a `composer.json` i'd be happy to merge it

**Comment by KristobalJunta** [comment]
@iamcal I really wanna do it, but right now I don't have much free time :cry: 
marktopper's solution works well as a fix, but that's definitely not the proper way

**Comment by mdoelker** [comment]
There you go #27

**Comment by KristobalJunta** [comment]
@mdoelker whoa it's that much easy. Thanks

**Comment by mdoelker** [comment]
You do have to submit it on packagist.org though once the file is merged.

**Comment by KristobalJunta** [comment]
Of course, I just forgot it's not obligatory to support PSR in composer packages

**Comment by iamcal** [comment]
thanks! PR merged and package registered: https://packagist.org/packages/iamcal/php-emoji
