### ISSUE TITLE
generate a map with the latest emoji available 

### ISSUE THREAD

**Issue by khammami** [iamcal/php-emoji#12]
Hi @iamcal 
I noticed that "http://www.unicode.org/~scherer/emoji4unicode/snapshot/full.html" is outdated and dosen't contains all emoji available in gemoji. I checked also emoji-data which is based on the same file "full.html" but also on "http://www.unicode.org/Public/UNIDATA/UnicodeData.txt" which is updated with all the missing emoji. 
my request is : could you please integrate the same process of emoji-data in php-emoji in order to generate a map with the latest emoji
thanks

**Comment by yhostc** [comment]
+1

**Comment by willianrodrigues** [comment]
+1

I don't have an available linux machine to rebuild the catalog.

**Comment by huangzhwork** [comment]
+1

**Comment by khammami** [comment]
@gr0g I already generated a new map but you have to check the missing emoji and them manually.

@gr0g @rkrv @gbrosenthal @yhostc @willianrodrigues @huangzhwork I recemmend you [emojione](https://github.com/Ranks/emojione). It's great and I'm using it in my projects. for php, [emojione](https://github.com/Ranks/emojione) use php-emoji of @iamcal  :+1:

**Comment by huangzhwork** [comment]
@khammami Perfect, It was just in time, I am modifying the generator and then received you reply
