### ISSUE TITLE
Not working.

### ISSUE THREAD

**Issue by dennisjerdz** [iamcal/php-emoji#14]
I recently included tested this on my localhost (using xampp) but the functions are returning the same values-- I expect them to be emoji's.

On my headers are:
<?php include("emoji/emoji.php"); ?>
and
link rel="stylesheet" type="text/css" media="all" href="emoji/emoji.css"

![function_notworking](https://cloud.githubusercontent.com/assets/9082261/8529491/3ae79248-244d-11e5-9a4c-17cab6cbdf1e.jpg)

**Comment by iamcal** [comment]
it looks like your input is just the string `"U+E63E"` rather than the UTF-8 bytes that would represent that codepoint - `\xEE\x98\xBE`

**Comment by dennisjerdz** [comment]
I only tested it on my localhost-- now I tried it on my site using my phone (allowing inputs from user), and it worked. Thank you iamcal!
