### ISSUE TITLE
Retina support

### ISSUE THREAD

**Issue by adrienbrault** [iamcal/php-emoji#17]
It looks like the image file of this project is not optimized for retina screens

**Comment by oliveratgithub** [comment]
> Latest commit 6d339a1  on Aug 27, 2013
This repo is outdated and - honestly - it's not required anymore today. I just implemented emojis with my PHP/MySQL website without using anything here.

**Comment by iamcal** [comment]
The project currently contains 64px images. Twitter and Emojione images do not come any bigger, although you could make a larger sheet for Apple or Google images from the emoji-data library. I don't have any plans to offer larger sheets at the moment.
