### ISSUE TITLE
Some emoticons leave residual data in the string after conversion

### ISSUE THREAD

**Issue by CedCannes** [iamcal/php-emoji#34]
I use emoji_unified_to_html
When I convert ❤️️ I have as result : 
`<span class="emoji-outer emoji-sizer"><span class="emoji-inner emoji2764"></span></span>️️`
with some residual data : `EF B8 8F EF B8 8F`

This emoji is supported by this replacement : 
`"\xe2\x9d\xa4"=>"<span class=\x22emoji-outer emoji-sizer\x22><span class=\x22emoji-inner emoji2764\x22></span></span>",`

but it seems that ❤️️ = `\xe2\x9d\xa4\xef\xb8\x8f\xef\xb8\x8f`  not only  `\xe2\x9d\xa4`

**Comment by iamcal** [comment]
`EF B8 8F` is `U+FE0F`, the variation selector for picture-mode-emoji. i need to update the library to support this

**Comment by iamcal** [comment]
fixed in v1.4.2

**Comment by CedCannes** [comment]
Thanks a lot.

**Comment by CedCannes** [comment]
Sorry, but I think there are still residual data for this one ❤️️  : U+FE0F
Before the modification it returned 2 * U+FE0F, now it does return 1 * U+FE0F.
