### ISSUE TITLE
Problem to send emoji to Push Notification

### ISSUE THREAD

**Issue by alexleandrom** [iamcal/php-emoji#7]
Hi everybody, I am trying to send pushnotification for ios app.
end I am having a problem to send emoji on this push.

I have this text on my database:

"\ue415 Vei na boa vou dar um tiro nesse push"

when I try to send this message to APN(https://github.com/duccio/ApnsPHP) it arrives

"\? Vei na boa vou dar um tiro nesse push"

Someone know how can I convert this?

**Comment by pashtika** [comment]
Does emoji works with APNS Java code? If yes, could you please share code snippet ?
